cluster1:
  tag: cluster1
  apps:
    grafana:
      namespace: grafana
      helm:
        applications: grafana-cluster-1
      destination:
        name: cluster-1
      valueFiles: 
        - values-cluster-1.yaml

    traefik:
      namespcae: traefik
      helm:
        applications: traefik-cluster-1
      destination:
        name: cluster-1
      valueFiles: 
        - values-cluster-1.yaml
        
cluster2:
  tag: cluster2
  apps:
    grafana:
      namespace: grafana
      helm:
        applications: grafana-cluster-2
      destination:
        name: cluster-2
      valueFiles: 
        - values-cluster-2.yaml

    traefik:
      namespcae: traefik
      helm:
        applications: traefik-cluster-2
      destination:
        name: cluster-2
      valueFiles: 
        - values-cluster-2.yaml
