apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ns-c2
  namespace: argocd
spec:
  destination:
    name: c2
    namespace: ns-c2
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: master
  syncPolicy:
    automated: {}
