---
tags:
  cluster-1: true
  cluster-2: false
traefik-cluster-1:
  deployment:
    kind: DaemonSet
  service:
    type: ClusterIP
  ports:
    web:
      port: 80
    websecure:
      port: 443
    # metrics:
    #   port: 19100
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
  ingressClass:
    enabled: true
  ingressRoute:
    dashboard:
      enabled: false
  logs:
    access:
      enabled: false
  hostNetwork: true
  # image:
  #   name: andreydockerhub/app
  #   tag: traefik_2.9.4
  # updateStrategy:
  #   rollingUpdate:
  #     maxUnavailable: 1
  #     maxSurge: 0
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0
  globalArguments: []
  nodeSelector:
    node-role.kubernetes.io/ingress: ""
  tolerations:
    - key: "node-role.kubernetes.io/ingress"
      operator: "Exists"
  securityContext:
    capabilities:
      drop: [ALL]
      add: [NET_BIND_SERVICE]
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
