---
tags:
  cluster-1: false
  cluster-2: true

traefik-cluster-2:
  deployment:
    kind: DaemonSet
  service:
    type: NodePort
  ports:
    web:
      port: 80
    # websecure:
    #   port: 443
    # metrics:
    #   port: 19100
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
    # - "--entryPoints.web.address=:80"
    # - "--entryPoints.web.forwardedHeaders.insecure"
    # - "--entryPoints.web.proxyProtocol.insecure"
    - "--entryPoints.web.forwardedHeaders.trustedIPs=192.168.31.0/24"
    - "--entryPoints.web.proxyProtocol.trustedIPs=192.168.31.0/24"
  ingressClass:
    enabled: true
  ingressRoute:
    dashboard:
      enabled: false
  logs:
    access:
      enabled: true
  hostNetwork: false
  # image:
  #   name: andreydockerhub/app
  #   tag: traefik_2.9.4
  # updateStrategy:
  #   rollingUpdate:
  #     maxUnavailable: 1
  #     maxSurge: 0
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0
  globalArguments: []
  nodeSelector:
    node-role.kubernetes.io/ingress: ""
  tolerations:
    - key: "node-role.kubernetes.io/ingress"
      operator: "Exists"
  securityContext:
    capabilities:
      drop: [ALL]
      add: [NET_BIND_SERVICE]
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
