---
tags:
  cluster-1: false
  cluster-2: true

traefik-cluster-2:
  deployment:
    kind: DaemonSet
  service:
    type: NodePort
  ports:
    web:
      port: 80
  additionalArguments:
    - "--serversTransport.insecureSkipVerify=true"
    - "--entryPoints.web.forwardedHeaders.trustedIPs=192.168.31.0/24"
    - "--entryPoints.web.proxyProtocol.trustedIPs=192.168.31.0/24"
  ingressClass:
    enabled: true
  ingressRoute:
    dashboard:
      enabled: false
  logs:
    access:
      enabled: true
  hostNetwork: false
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0
  globalArguments: []
  nodeSelector:
    node-role.kubernetes.io/ingress: ""
  tolerations:
    - key: "node-role.kubernetes.io/ingress"
      operator: "Exists"
  securityContext:
    capabilities:
      drop: [ALL]
      add: [NET_BIND_SERVICE]
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
