apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: testproject
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example project used to demonstrate Declarative deployments in ArgoCD
  sourceRepos:
  - '*'
  destinations:
  - namespace: testnamespace
    name: in-cluster