apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: main
spec:
  generators:
  - list:
      elements:
      - cluster: cluster-1
        url: https://kubernetes.default.svc
      - cluster: cluster-2
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'main-applications-{{cluster}}'
    spec:
      syncPolicy:
        automated: {}
      project: default
      source:
        repoURL: git@github.com:Andrik001/ar.git
        targetRevision: HEAD
        path: 'HelmCharts/{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: argocd
