---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app-cluster-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Andrik001/ar.git
    targetRevision: main
    path: 'charts/argocd'
    helm:
      parameters:
        - name: "cluster2.enable"
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
