apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-cluster-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Andrik001/ar.git'
    path: charts/grafana
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-cluster-2.yaml
  destination:
    name: cluster-2
    namespace: grafana
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true