apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Andrik001/ar.git'
    path: HelmCharts/traefik
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-cluster-2.yaml
  destination:
    name: cluster-2