{{- range .Values.app := $app }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-cluster-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Andrik001/ar.git'
    path: HelmCharts/{{ $app.helm.applications }}
    targetRevision: HEAD
    helm:
      valueFiles:
         - values-cluster-1.yaml
        # {{- range .Values.grafana.valueFiles }}
        # - {{ . | print | quote }}
        # {{- end }}
  destination:
    name: cluster-1
    namespace: {{ $app.helm.applications }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end }}