apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-cluster-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Andrik001/ar.git'
    path: HelmCharts/{{ .Values.helm.applications }}
    targetRevision: HEAD
    helm:
      {{- with .Values.helm.applications.valueFiles }}
      valueFiles: 
          {{- toYaml . | nindent 8 }}
      {{- end }} 
  destination:
    name: cluster-1
    namespace: {{ .Values.helm.applications }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true