apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-cluster-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Andrik001/ar.git'
    path: HelmCharts/{{ .Values.helm.applications}}
    targetRevision: HEAD
    helm:
      valueFiles: 
        - values-cluster-1.yaml 
  destination:
    name: cluster-1
    namespace: grafana
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true