{{- range .Values.app }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-cluster-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Andrik001/ar.git'
    path: HelmCharts/{{ . | print }}
    targetRevision: HEAD
    helm:
      valueFiles: 
        {{- range .valueFiles }}
        - {{ . | print | quote }}
        {{- end }}
  destination:
    name: cluster-1
    namespace: {{ .helm.applications }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end }}