{{- range $appName, $app := .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.helm.applications }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Andrik001/ar.git'
    path: HelmCharts/{{ $appName }}
    targetRevision: HEAD
    helm:
      valueFiles:
        {{- range $app.valueFiles }}
        - {{ . }}
        {{- end }}
  destination:
    name: {{ $app.destination.name }}
    namespace: {{ $appName }}
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
{{- end }}